name: app_nasa
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  location: 1.4.1
  dio: ^3.0.3
  onesignal_flutter: ^2.1.0
  material_design_icons_flutter: ^3.2.4595
  flare_flutter: 1.6.2
  intro_views_flutter:




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/flare.flr
    - assets/marcador.flr
    - assets/234049726023202.jpg
    - assets/ProcessingLogo.flr